language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=cakephp_test' db_database='cakephp_test' db_username='travis' db_password=''
    - DB=pgsql db_class='Cake\Database\Driver\Postgres' db_dsn='postgres://postgres@127.0.0.1/cakephp_test' db_database='cakephp_test' db_username='travis' db_password=''
  global:
    - DEFAULT=1 CI=1

matrix:
  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.0
      env: COVERALLS=1 DEFAULT=0 DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=cakephp_test' db_database='cakephp_test' db_username='travis' db_password=''

  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - if [ $DB = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [ $DB = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

  - if [ $PHPCS != 1 ]; then composer require phpunit/phpunit; fi
  - if [ $COVERALLS = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi
  - if [ $COVERALLS = '1' ]; then mkdir -p build/logs; fi

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - if [ $COVERALLS = '1' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ $COVERALLS = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi
  - if [ $DEFAULT = '1' ]; then vendor/bin/phpunit; fi
  - if [ $PHPCS = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml --ignore=vendor --ignore=docs --ignore=test_files --ignore=config/Migrations . ; fi

notifications:
  email: false
